### ISSUE TITLE
CPS reset timeout (fe1a not appearing on PCI bus and system needs hard power)

### ISSUE THREAD

**Issue by dlobete** [platinasystems/go#4] opened 2017-01-03 19:26 UTC
Need to hard-reset/unreset of fe1a instead of soft/cps reset.
Should "goes stop" put fe1a into hard-reset ? Probably if in a panic situation but for a sw upgrade where fe1a is expected to be back up in a very short time not i.e. it would seem ok to have fe1a forward packets while headless for a short time but not indefinitely.

**Comment by jasonlpang** [comment] 2017-03-07 23:09
I think we should toggle the TH hardware reset via i2c gpio at goes start, stop, and uninstall.  This would fix the TH pcie reboot issue. For now, we can also recommend users to do goes stop before resetting linux to avoid headless TH operation.  

To avoid headless TH operation automatically, we can add a feature in the CPU card CPLD to detect CPU reset and have the CPLD reset the TH.  We have hooks in the hardware to support this.  We'd likely have a CPLD register enable bit for this feature so that it can be disabled if we ever want to support hitless cpu/linux reset.

**Comment by jasonlpang** [comment] 2017-06-06 18:01
This issue is caused by the x86 performing a cold reboot which power cycles the x86.  This power cycle causes the TH to require a hard reset to come back up on PCIe.

With AMI BIOS, in debian "reboot" command performs a cold reboot while the "reboot -f" command performs a warm reboot.  With coreboot, the intel FSP will perform a cold reboot regardless of linux side command.  We are working with intel to figure out how to support warm reboot with the FSP.

In the mean time, with Alpha units (invader1-15) to avoid this issue use AMI BIOS and "reboot -f" or issue the following commands to hard reset the TH before launching goes:
sudo i2cset -y 0x0 0x74 0x6 0xf8
sudo i2cset -y 0x0 0x74 0x2 0xfc
sudo i2cset -y 0x0 0x74 0x2 0xff
sudo echo 1 > /sys/bus/pci/rescan
sudo rmmod uio_pci_dma
sudo insmod <path_to>/uio_pci_dma.ko

With Beta units and beyond (invader16-24), this issue does not occur with CPLD v8 or higher or with the "reboot -f" command with lower CPLD versions.  Check CPLD version with the ioget tool (sudo ./ioget 0x600).

**Comment by jasonlpang** [comment] 2017-12-13 00:41
Closing.  Tomahawk reset is executed at Goes start by software.

**Closed by jasonlpang** 2017-12-13 00:41 UTC
