### ISSUE TITLE
index out of range on goes start

### ISSUE THREAD

**Issue by fszyang** [platinasystems/go#18] opened 2017-02-04 23:24 UTC
Getting "index out of range" error in syslog on goes start.  vnetd wouldn't launch.  Doesn't happen all the time.

version: 6fa4a9f8172459f10a52b0a75f455a7a25b1da48

12300 ?        Ssl    0:00 goes-daemons
12306 ?        Sl     0:00  \_ redisd
12321 ?        Sl     0:00  \_ uptimed
12322 ?        Sl     0:00  \_ nld

/var/log/syslog:
...
Feb  4 15:13:16 invader17 goes.vnetd[12326]: runtime error: index out of range: goroutine 36 [running]:
Feb  4 15:13:16 invader17 goes.vnetd[12326]: runtime/debug.Stack(0xc420046610, 0xa46000, 0xc42000c0a0)
Feb  4 15:13:16 invader17 goes.vnetd[12326]:         /usr/local/go/src/runtime/debug/stack.go:24 +0x79
Feb  4 15:13:16 invader17 goes.vnetd[12326]: github.com/platinasystems/go/elib/loop.(*Loop).doEvent.func1(0xc420194000)
Feb  4 15:13:16 invader17 goes.vnetd[12326]:         /home/fyang/gopath/src/github.com/platinasystems/go/elib/loop/event.go:128 +0x91
Feb  4 15:13:16 invader17 goes.vnetd[12326]: panic(0xa46000, 0xc42000c0a0)
Feb  4 15:13:16 invader17 goes.vnetd[12326]:         /usr/local/go/src/runtime/panic.go:458 +0x243
Feb  4 15:13:16 invader17 goes.vnetd[12326]: github.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/fe1a.(*pipe_counter_eviction_fifo_elt).evict_pool
_counter(0xc420046768, 0xc420218000, 0xc42022c180, 0x0)
Feb  4 15:13:16 invader17 goes.vnetd[12326]:         /home/fyang/gopath/src/github.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/fe1a/pipe_counters
.go:585 +0xcd
Feb  4 15:13:16 invader17 goes.vnetd[12326]: github.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/fe1a.(*fe1a).decode_eviction_fifo(0xc420218000, 0
xc420ed8138, 0x3, 0x3fb2)
Feb  4 15:13:16 invader17 goes.vnetd[12326]:         /home/fyang/gopath/src/github.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/fe1a/pipe_counters
.go:660 +0x32c
Feb  4 15:13:16 invader17 goes.vnetd[12326]: github.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/fe1a.(*fe1a).handle_fifo_data(0xc420218000, 0xc42
0ed8000, 0x2eec, 0x4000, 0xc4203eb380)
Feb  4 15:13:16 invader17 goes.vnetd[12326]:         /home/fyang/gopath/src/github.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/fe1a/pipe_counters
.go:330 +0xaa
Feb  4 15:13:16 invader17 goes.vnetd[12326]: github.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/fe1a.(*fe1a).pipe_counter_eviction_fifo_sync(0xc4
20218000)
Feb  4 15:13:16 invader17 goes.vnetd[12326]:         /home/fyang/gopath/src/github.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/fe1a/pipe_counters
.go:343 +0x75
Feb  4 15:13:16 invader17 goes.vnetd[12326]: github.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/fe1a.(*fe1a).get_port_counters_helper(0xc42021800
0, 0xc42035de60, 0xc4209d8a20, 0xc420040000)
Feb  4 15:13:16 invader17 goes.vnetd[12326]:         /home/fyang/gopath/src/github.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/fe1a/port_counters
.go:308 +0x764
Feb  4 15:13:16 invader17 goes.vnetd[12326]: github.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/fe1a.(*fe1a).get_port_counters(0xc420218000, 0xc4
2035de60, 0xc4209d8a20)
Feb  4 15:13:16 invader17 goes.vnetd[12326]:         /home/fyang/gopath/src/github.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/fe1a/port_counters
.go:153 +0x46
Feb  4 15:13:16 invader17 goes.vnetd[12326]: github.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/fe1a.(*Port).GetHwInterfaceCounterValues(0xc42035
de60, 0xc4209d8a20)
Feb  4 15:13:16 invader17 goes.vnetd[12326]:         /home/fyang/gopath/src/github.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/fe1a/port_init.go:
158 +0x5d
Feb  4 15:13:16 invader17 goes.vnetd[12326]: github.com/platinasystems/go/vnet.(*interfaceMain).foreachHwIfCounter(0xc4201946f8, 0x752035e001, 0xc420047e80)
Feb  4 15:13:16 invader17 goes.vnetd[12326]:         /home/fyang/gopath/src/github.com/platinasystems/go/vnet/interface_counter.go:233 +0xd3
Feb  4 15:13:16 invader17 goes.vnetd[12326]: github.com/platinasystems/go/vnet.(*Vnet).ForeachHwIfCounter(0xc420194000, 0x4014000000000101, 0xc420047ee0)
Feb  4 15:13:16 invader17 goes.vnetd[12326]:         /home/fyang/gopath/src/github.com/platinasystems/go/vnet/interface_counter.go:258 +0x12d
Feb  4 15:13:16 invader17 goes.vnetd[12326]: github.com/platinasystems/go/internal/optional/vnetd.(*ifStatsPoller).EventAction(0xc420194a30)
Feb  4 15:13:16 invader17 goes.vnetd[12326]:         /home/fyang/gopath/src/github.com/platinasystems/go/internal/optional/vnetd/vnetd.go:286 +0x8d
Feb  4 15:13:16 invader17 goes.vnetd[12326]: github.com/platinasystems/go/elib/loop.(*loopEvent).do(0xc42014f980)
Feb  4 15:13:16 invader17 goes.vnetd[12326]:         /home/fyang/gopath/src/github.com/platinasystems/go/elib/loop/event.go:118 +0x34
Feb  4 15:13:16 invader17 goes.vnetd[12326]: github.com/platinasystems/go/elib/loop.(*Loop).doEvent(0xc420194000, 0xc42014f980)
Feb  4 15:13:16 invader17 goes.vnetd[12326]:         /home/fyang/gopath/src/github.com/platinasystems/go/elib/loop/event.go:133 +0x51
Feb  4 15:13:16 invader17 goes.vnetd[12326]: github.com/platinasystems/go/elib/loop.(*Loop).eventHandler(0xc420194000, 0x12320e0, 0xc420194548)
Feb  4 15:13:16 invader17 goes.vnetd[12326]:         /home/fyang/gopath/src/github.com/platinasystems/go/elib/loop/event.go:140 +0x86
Feb  4 15:13:16 invader17 goes.vnetd[12326]: created by github.com/platinasystems/go/elib/loop.(*Loop).startHandler
Feb  4 15:13:16 invader17 goes.vnetd[12326]:         /home/fyang/gopath/src/github.com/platinasystems/go/elib/loop/event.go:153 +0x124
Feb  4 15:13:19 invader17 goes.vnetd[12326]: done

**Comment by fszyang** [comment] 2017-02-06 21:02
FYI, vnet.ready is set before it goes down, so sometimes between checking vnet.ready and sourcing /etc/goes/start was when vnet goes down because of index out of range.  Doesn't happen all the time.  About 1 in 15 "goes restart" tries.

fyang@invader17:~$ sudo goes restart
Checking if vnet.ready...
passed. vnet.ready = true err = <nil>
hset: read unix @->/run/goes/socks/redisd: i/o timeout  <---first hset in /etc/goes/start
hset: read unix @->/run/goes/socks/redisd: i/o timeout
hset: read unix @->/run/goes/socks/redisd: i/o timeout
...
fyang@invader17:~$ ls /run/goes/socks/
nld  redisd  redis-pub  redis-reg
fyang@invader17:~$

**Comment by dlobete** [comment] 2017-02-06 22:10
Frank,
Does this happen without goes/start script? That would prove the hsets are
happening in an early window.
Don.

**Comment by fszyang** [comment] 2017-02-06 22:53
No scripting.  I was just typing "sudo goes restart" by hand.  I see this sometimes doing goes install as well.

**Comment by dlobete** [comment] 2017-02-06 22:56
I meant you are using commands in /etc/goes/start correct? My question was
does the panic happen if you don't have that file.
Don.

**Comment by fszyang** [comment] 2017-02-06 23:26
Got it.
I took out all the "hset" in /etc/goes/start; the file looks like this now:
"
#!/usr/bin/goes
! ifup --allow vnet -a

Retest with 30 "goes restart" and vnetd comes up every time.

**Comment by dlobete** [comment] 2017-02-06 23:31
Thanks - that gives us a clue that an early hset is a problem.
Don.

**Comment by dlobete** [comment] 2017-02-08 00:45
Frank,
Could you add the contents of the /etc/goes/start file to this issue?
Thanks,
Don.

**Comment by fszyang** [comment] 2017-02-08 02:31
Here's the /etc/goes/start that can crash vnet sometimes:

#!/usr/bin/goes

hset -q platina vnet.eth-1-1.media copper
hset -q platina vnet.eth-1-1.speed auto

hset -q platina vnet.eth-2-1.media copper
hset -q platina vnet.eth-2-1.speed auto

hset -q platina vnet.eth-3-1.media copper
hset -q platina vnet.eth-3-1.speed auto

hset -q platina vnet.eth-4-1.media copper
hset -q platina vnet.eth-4-1.speed auto

hset -q platina vnet.eth-5-1.media copper
hset -q platina vnet.eth-5-1.speed auto

hset -q platina vnet.eth-6-1.media copper
hset -q platina vnet.eth-6-1.speed auto

hset -q platina vnet.eth-7-1.media copper
hset -q platina vnet.eth-7-1.speed auto

hset -q platina vnet.eth-8-1.media copper
hset -q platina vnet.eth-8-1.speed auto

hset -q platina vnet.eth-9-1.media copper
hset -q platina vnet.eth-9-1.speed auto

hset -q platina vnet.eth-10-1.media copper
hset -q platina vnet.eth-10-1.speed auto

hset -q platina vnet.eth-11-1.media copper
hset -q platina vnet.eth-11-1.speed auto

hset -q platina vnet.eth-12-1.media copper
hset -q platina vnet.eth-12-1.speed auto

hset -q platina vnet.eth-13-1.media copper
hset -q platina vnet.eth-13-1.speed auto

hset -q platina vnet.eth-14-1.media copper
hset -q platina vnet.eth-14-1.speed auto

hset -q platina vnet.eth-15-1.media copper
hset -q platina vnet.eth-15-1.speed auto

hset -q platina vnet.eth-16-1.media copper
hset -q platina vnet.eth-16-1.speed auto

hset -q platina vnet.eth-17-1.media copper
hset -q platina vnet.eth-17-1.speed 100g

hset -q platina vnet.eth-18-1.media copper
hset -q platina vnet.eth-18-1.speed 100g

hset -q platina vnet.eth-19-1.media copper
hset -q platina vnet.eth-19-1.speed 100g

hset -q platina vnet.eth-20-1.media copper
hset -q platina vnet.eth-20-1.speed 100g

hset -q platina vnet.eth-21-1.media copper
hset -q platina vnet.eth-21-1.speed 100g

hset -q platina vnet.eth-22-1.media copper
hset -q platina vnet.eth-22-1.speed 100g

hset -q platina vnet.eth-23-1.media copper
hset -q platina vnet.eth-23-1.speed 100g

hset -q platina vnet.eth-24-1.media copper
hset -q platina vnet.eth-24-1.speed 100g

hset -q platina vnet.eth-25-1.media copper
hset -q platina vnet.eth-25-1.speed 40g

hset -q platina vnet.eth-26-1.media copper
hset -q platina vnet.eth-26-1.speed 40g

hset -q platina vnet.eth-27-1.media copper
hset -q platina vnet.eth-27-1.speed 40g

hset -q platina vnet.eth-28-1.media copper
hset -q platina vnet.eth-28-1.speed 40g

hset -q platina vnet.eth-29-1.media copper
hset -q platina vnet.eth-29-1.speed 40g

hset -q platina vnet.eth-30-1.media copper
hset -q platina vnet.eth-30-1.speed auto

hset -q platina vnet.eth-31-1.media copper
hset -q platina vnet.eth-31-1.speed 40g

hset -q platina vnet.eth-32-1.media copper
hset -q platina vnet.eth-32-1.speed auto

! ifup --allow vnet -a

**Comment by dlobete** [comment] 2017-02-13 22:01
Is there traffic running constantly during your test? I tried over 500 goes start/stop sequences without reproducing this.

**Comment by fszyang** [comment] 2017-02-13 22:50
Yes, I have traffic from pktgen constantly sending while the stop/start is happening.

**Comment by rcoulson-platina** [comment] 2017-02-15 23:12
Good afternoon.

We believe that the commit below will help us isolate the array
out-of-bounds panic seen above by providing array index information if
either pipe or index is invalid; please re-run this test so we can collect
panic information, if available.

thank you,

Don & Rob.

commit 8194742fd872c7eaf5ae1ff3d77d0d2afce0afd4
Author: Robert Coulson <rcoulson@platinasystems.com>
Date:   Wed Feb 15 14:56:16 2017 -0800

    internal (fe1a): add pool counter array boundary verification

    We've seen panic's due to array out-of-bounds, so to isolate
    the root cause, boundary checking was added to trap and panic
    on this condition.

    Signed-off-by: Robert Coulson <rcoulson@platinasystems.com>

**Comment by fszyang** [comment] 2017-03-08 04:44
Rob,

With your latest private image "_wpanic_reset", here's the experimental result in the testbed running goes stop/start repeatedly.

In 260 loops, vnetd failed 25 times
Summary of panics in syslog:

tx ring full, 10 times
Mar  7 20:08:58 invader17 goes.vnetd[23721]: panic: tx ring full
Mar  7 20:08:58 invader17 goes.vnetd[23721]:
Mar  7 20:08:58 invader17 goes.vnetd[23721]: goroutine 318 [running]:
Mar  7 20:08:58 invader17 goes.vnetd[23721]: panic(0xb73180, 0xc8211b80a0)
Mar  7 20:08:58 invader17 goes.vnetd[23721]:         /usr/local/go/src/runtime/panic.go:464 +0x3e6
Mar  7 20:08:58 invader17 goes.vnetd[23721]: github.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/packet.(*InterfaceNode).output(0xc82034ebb0, 0xc8202042e0, 0xc8231d82c0)
Mar  7 20:08:58 invader17 goes.vnetd[23721]:         /home/rcoulson/gopath/src/github.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/packet/tx.go:283 +0x10c
Mar  7 20:08:58 invader17 goes.vnetd[23721]: github.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/packet.(*InterfaceNode).InterfaceOutput(0xc82034ebb0, 0xc8231d82c0)
Mar  7 20:08:58 invader17 goes.vnetd[23721]:         /home/rcoulson/gopath/src/github.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/packet/tx.go:362 +0xb5
Mar  7 20:08:58 invader17 goes.vnetd[23721]: github.com/platinasystems/go/vnet.(*interfaceNode).ifOutputThread(0xc82034ebb0)
Mar  7 20:08:58 invader17 goes.vnetd[23721]:         /home/rcoulson/gopath/src/github.com/platinasystems/go/vnet/interface_node.go:138 +0x98
Mar  7 20:08:58 invader17 goes.vnetd[23721]: created by github.com/platinasystems/go/vnet.(*interfaceNode).setupTx
Mar  7 20:08:58 invader17 goes.vnetd[23721]:         /home/rcoulson/gopath/src/github.com/platinasystems/go/vnet/interface_node.go:76 +0xe3

Index out of range, 10 times
Mar  7 20:09:41 invader17 goes.vnetd[28868]: runtime error: index out of range: goroutine 36 [running]:
Mar  7 20:09:41 invader17 goes.vnetd[28868]: runtime/debug.Stack(0x0, 0x0, 0x0)
Mar  7 20:09:41 invader17 goes.vnetd[28868]:         /usr/local/go/src/runtime/debug/stack.go:24 +0x80
Mar  7 20:09:41 invader17 goes.vnetd[28868]: github.com/platinasystems/go/elib/loop.(*Loop).doEvent.func1(0xc82018a000)
Mar  7 20:09:41 invader17 goes.vnetd[28868]:         /home/rcoulson/gopath/src/github.com/platinasystems/go/elib/loop/event.go:128 +0xa2
Mar  7 20:09:41 invader17 goes.vnetd[28868]: panic(0xd82080, 0xc82000a030)
Mar  7 20:09:41 invader17 goes.vnetd[28868]:         /usr/local/go/src/runtime/panic.go:426 +0x4e9
Mar  7 20:09:41 invader17 goes.vnetd[28868]: github.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/fe1a.(*pipe_counter_eviction_fifo_elt).evict_pool_counter(0xc82037a978, 0xc8201fa000, 0xc82020e190, 0x0)
Mar  7 20:09:41 invader17 goes.vnetd[28868]:         /home/rcoulson/gopath/src/github.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/fe1a/pipe_counters.go:585 +0x122
Mar  7 20:09:41 invader17 goes.vnetd[28868]: github.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/fe1a.(*fe1a).decode_eviction_fifo(0xc8201fa000, 0xc820f64060, 0x3, 0x3fe8)
Mar  7 20:09:41 invader17 goes.vnetd[28868]:         /home/rcoulson/gopath/src/github.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/fe1a/pipe_counters.go:664 +0x7ee
Mar  7 20:09:41 invader17 goes.vnetd[28868]: github.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/fe1a.(*fe1a).handle_fifo_data(0xc8201fa000, 0xc820f64000, 0x2e98, 0x4000, 0xc8203e3260)
Mar  7 20:09:41 invader17 goes.vnetd[28868]:         /home/rcoulson/gopath/src/github.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/fe1a/pipe_counters.go:330 +0xca
Mar  7 20:09:41 invader17 goes.vnetd[28868]: github.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/fe1a.(*fe1a).pipe_counter_eviction_fifo_sync(0xc8201fa000)
Mar  7 20:09:41 invader17 goes.vnetd[28868]:         /home/rcoulson/gopath/src/github.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/fe1a/pipe_counters.go:343 +0x9d
Mar  7 20:09:41 invader17 goes.vnetd[28868]: github.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/fe1a.(*fe1a).get_port_counters_helper(0xc8201fa000, 0xc820345890, 0xc820c8b620, 0xc820180000)
Mar  7 20:09:41 invader17 goes.vnetd[28868]:         /home/rcoulson/gopath/src/github.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/fe1a/port_counters.go:308 +0x2909
Mar  7 20:09:41 invader17 goes.vnetd[28868]: github.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/fe1a.(*fe1a).get_port_counters(0xc8201fa000, 0xc820345890, 0xc820c8b620)
Mar  7 20:09:41 invader17 goes.vnetd[28868]:         /home/rcoulson/gopath/src/github.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/fe1a/port_counters.go:153 +0x47
Mar  7 20:09:41 invader17 goes.vnetd[28868]: github.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/fe1a.(*Port).GetHwInterfaceCounterValues(0xc820345890, 0xc820c8b620)
Mar  7 20:09:41 invader17 goes.vnetd[28868]:         /home/rcoulson/gopath/src/github.com/platinasystems/go/vnet/devices/ethernet/switch/fe1/internal/fe1a/port_init.go:158 +0x59
Mar  7 20:09:41 invader17 goes.vnetd[28868]: github.com/platinasystems/go/vnet.(*interfaceMain).foreachHwIfCounter(0xc82018a6f8, 0xa920345a01, 0xc82037be08)
Mar  7 20:09:41 invader17 goes.vnetd[28868]:         /home/rcoulson/gopath/src/github.com/platinasystems/go/vnet/interface_counter.go:233 +0x124
Mar  7 20:09:41 invader17 goes.vnetd[28868]: github.com/platinasystems/go/vnet.(*Vnet).ForeachHwIfCounter(0xc82018a000, 0x4014000000000101, 0xc82037be48)
Mar  7 20:09:41 invader17 goes.vnetd[28868]:         /home/rcoulson/gopath/src/github.com/platinasystems/go/vnet/interface_counter.go:258 +0x18b
Mar  7 20:09:41 invader17 goes.vnetd[28868]: github.com/platinasystems/go/internal/optional/vnetd.(*ifStatsPoller).EventAction(0xc82018aa30)
Mar  7 20:09:41 invader17 goes.vnetd[28868]:         /home/rcoulson/gopath/src/github.com/platinasystems/go/internal/optional/vnetd/vnetd.go:311 +0x82
Mar  7 20:09:41 invader17 goes.vnetd[28868]: github.com/platinasystems/go/elib/loop.(*loopEvent).do(0xc8203dd080)
Mar  7 20:09:41 invader17 goes.vnetd[28868]:         /home/rcoulson/gopath/src/github.com/platinasystems/go/elib/loop/event.go:118 +0x135
Mar  7 20:09:41 invader17 goes.vnetd[28868]: github.com/platinasystems/go/elib/loop.(*Loop).doEvent(0xc82018a000, 0xc8203dd080)
Mar  7 20:09:41 invader17 goes.vnetd[28868]:         /home/rcoulson/gopath/src/github.com/platinasystems/go/elib/loop/event.go:133 +0x48
Mar  7 20:09:41 invader17 goes.vnetd[28868]: github.com/platinasystems/go/elib/loop.(*Loop).eventHandler(0xc82018a000, 0x7f692832b2c0, 0xc82018a548)
Mar  7 20:09:41 invader17 goes.vnetd[28868]:         /home/rcoulson/gopath/src/github.com/platinasystems/go/elib/loop/event.go:140 +0x81
Mar  7 20:09:41 invader17 goes.vnetd[28868]: created by github.com/platinasystems/go/elib/loop.(*Loop).startHandler
Mar  7 20:09:41 invader17 goes.vnetd[28868]:         /home/rcoulson/gopath/src/github.com/platinasystems/go/elib/loop/event.go:153 +0x120
Mar  7 20:09:44 invader17 goes.vnetd[28868]: done

NLMSG_ERROR, 5 times
Mar  7 20:09:18 invader17 goes.vnetd[27753]: panic: NLMSG_ERROR:
Mar  7 20:09:18 invader17 goes.vnetd[27753]: len: 60
Mar  7 20:09:18 invader17 goes.vnetd[27753]: seq: 12
Mar  7 20:09:18 invader17 goes.vnetd[27753]: pid: 27753
Mar  7 20:09:18 invader17 goes.vnetd[27753]: error: invalid argument
Mar  7 20:09:18 invader17 goes.vnetd[27753]: req: RTM_SETLINK
Mar  7 20:09:18 invader17 goes.vnetd[27753]: len: 40
Mar  7 20:09:18 invader17 goes.vnetd[27753]: seq: 12
Mar  7 20:09:18 invader17 goes.vnetd[27753]: pid: 27753
Mar  7 20:09:18 invader17 goes.vnetd[27753]: flags: Request
Mar  7 20:09:18 invader17 goes.vnetd[27753]: : invalid argument
Mar  7 20:09:18 invader17 goes.vnetd[27753]:
Mar  7 20:09:18 invader17 goes.vnetd[27753]: goroutine 101 [running]:
Mar  7 20:09:18 invader17 goes.vnetd[27753]: panic(0xd24e40, 0xc8204a7300)
Mar  7 20:09:18 invader17 goes.vnetd[27753]:         /usr/local/go/src/runtime/panic.go:464 +0x3e6
Mar  7 20:09:18 invader17 goes.vnetd[27753]: github.com/platinasystems/go/vnet/unix.(*netlinkMain).LoopInit(0xc8201aa4f8, 0xc8200dcb00)
Mar  7 20:09:18 invader17 goes.vnetd[27753]:         /home/rcoulson/gopath/src/github.com/platinasystems/go/vnet/unix/netlink.go:176 +0x1e6
Mar  7 20:09:18 invader17 goes.vnetd[27753]: github.com/platinasystems/go/elib/loop.(*Loop).callInitNode.func1.1(0x7fe07ae0d3d0, 0xc8201aa4f8, 0xc8200dcb00, 0xc8200dcbe0)
Mar  7 20:09:18 invader17 goes.vnetd[27753]:         /home/rcoulson/gopath/src/github.com/platinasystems/go/elib/loop/loop.go:415 +0x31
Mar  7 20:09:18 invader17 goes.vnetd[27753]: created by github.com/platinasystems/go/elib/loop.(*Loop).callInitNode.func1
Mar  7 20:09:18 invader17 goes.vnetd[27753]:         /home/rcoulson/gopath/src/github.com/platinasystems/go/elib/loop/loop.go:417 +0x90
Mar  7 20:09:21 invader17 goes.vnetd[27753]: exit status 2

**Comment by donnlee** [comment] 2017-05-16 21:23
Closing per @fszyang

**Closed by donnlee** 2017-05-16 21:23 UTC
